### PR TITLE
genomecov new features

### PR DESCRIPTION
**Pull request by portah**
enable genomecov to calculate coverage with specific fragment size (usually in ChIP-seq) and special case for pair-end experiment coverage from the most left point to the most right point of pair reads (also usually for ChIP-seq)

### CODE REVIEW

**Comment by portah** [comment]
Just address this post http://bedtools.readthedocs.org/en/latest/content/tools/genomecov.html#comment-2124658964

**Comment by arq5x** [comment]
Thanks very much for this contribution - I will have a close look and make sure I understand the biological application asap.

**Comment by portah** [comment]
In ChiP-Seq the binding site is usually not at the coordinate where reads map, but in the middle of the fragment. For this reason we often try to estimate average fragment size and extend the reads in the 5’-3’ direction up to the estimated fragment length. This “coverage by estimated fragments” graph is expected to peak at the actual binding site (and also looks better that actual or shifted reads ;)

**Comment by arq5x** [comment]
Would you mind embellishing the docs to explain these options and provide example?  I don't feel capable writing proper docs. If you have examples of plots or figures to guide the docs, that would be very useful. We will be happy to add you to the list of contributors. Thanks so much.

**Comment by portah** [comment]
I have added documentation. If you are interested in links to the papers I can also provide links/PMIDes

**Comment by portah** [comment]
Hi Aaron,
Should I add something to this pull request?

**Comment by arq5x** [comment]
Nope, I just need to free up time to integrate things. Sorry, just super busy.

**Comment by arq5x** [comment]
Thanks much for this!

**Comment by s1437643** [comment]
Apologies for reopening this pull request but would you be able to incorporate these new features in the coverage command? It would help a lot in situations where you want to calculate coverage over specific regions, like called peaks.

**Pull request merged**
