### PR TITLE
Non-recursive make (in the existing style)

### PR DESCRIPTION
**Pull request by jmarshall**
Rather some time ago, I offered to @arq5x that I would revamp the existing build system to be non-recursive and a bit cleaner, but still in its existing style of GNU Make and a snippet in each source subdirectory.

This is that; it needs a little more work (to the bamtools build and the git version generation) to fully support a separate objdir build.

### CODE REVIEW

**Comment by arq5x** [comment]
This is great, I am hoping to dig into this next week - I have been very overwhelmed with tasks outside of development!

**Comment by arq5x** [comment]
JUst realizing I never merged this!

**Comment by jmarshall** [comment]
It would be great to merge one or the other of these makefile refreshes :smile:

I'm happy to update it to the current state of bedtools — unless you're keen to do that bit!

**Comment by arq5x** [comment]
I have to admit that I am a bit rusty with Make and was never all that skilled to begin with. If it is easy for you to update the patch, I would be grateful, but if not, I could use this as a start and take it as an opportunity to learn how to do it!

**Comment by jmarshall** [comment]
No problem, it'd be fairly easy for me to do. Should be able to have a look over the weekend.

**Comment by arq5x** [comment]
That would be really fantastic; thank you - again

**Comment by jmarshall** [comment]
This is now updated to current **master**. Hopefully the makefile techniques used are somewhat comprehensible!

The header dependency generation is the complex bit, and it might be good to test it on the elderly compilers that some folks are using — though the compiler options used (`-MT foo -MMD -MP -MF bar.Td` have been around for a number of years.

You may find that this speeds up compilation when only one or two files have changed quite significantly.

**Comment by arq5x** [comment]
This is great, thanks @jmarshall ! The only thing I notice is that when I clone your changes, it is compiling as version `v2.19.1-827-gd1024d4e`. Perhaps this is an artifact in the .git log in your fork?

**Comment by jmarshall** [comment]
Yes, that's just an artifact of how long ago I forked bedtools. I've just pushed your master and several years worth of bedtools2 tags to my fork, so if you did this again now you'd see `v2.28.0-20-gd1024d4e` from a clone of my fork.

The one makefile thing left on my to-do list would be to change the `autoversion` rule to generate the new version_git.h via the same technique as HTSlib uses, which is the last piece required so that `make` in an untouched previously-built directory just says `make: Nothing to be done for 'all'.`.

But it'd probably be better to merge this and get it bedded in than wait for one more vaguely-related commit…

**Comment by arq5x** [comment]
Got it, thanks!

**Comment by jmarshall** [comment]
:tada:

Huzzah! (Hopefully this works well on people's CentOS 6 installations… :smile:)

**Pull request merged**
