### PR TITLE
Make sure all literal blocks are separated from their preceding double colon

### PR DESCRIPTION
**Pull request by rmzelle**
Fixes https://github.com/arq5x/bedtools2/issues/500

### CODE REVIEW

**Comment by rmzelle** [comment]
@arq5x, ready for squashing.

**Comment by arq5x** [comment]
Thanks!!!

**Comment by rmzelle** [comment]
(once you merge this, I'll create another PR to update the documentation of the "bedtools sort" tool, which isn't complete)

**Comment by rmzelle** [comment]
Bump. (I have another change to the documentation I'd like to submit as a pull request, but that would probably conflict with this PR if this isn't merged first)

**Comment by arq5x** [comment]
Sorry!

**Comment by rmzelle** [comment]
Great, thanks.

**Pull request merged**
