### PR TITLE
Rename "version" to avoid clash with STL

### PR DESCRIPTION
**Pull request by arjanvandervelde**
With C++20 version.h is part of STL; rename local version to avoid
clash. Currently compile fails with clang-9.

### CODE REVIEW

**Comment by jmarshall** [comment]
> With C++20 version.h is part of STL

Citation?

**Comment by arjanvandervelde** [comment]
@jmarshall https://en.cppreference.com/w/cpp/header/version

https://build.macports.org/builders/ports-10.6_x86_64-watcher/builds/5023

**Comment by jmarshall** [comment]
`#include <version>` is in C++20, but `#include "version.h"` is a different thing.

Thank you for the link to the failing build logs. The actual problem here is the file _src/utils/gzstream/version_, which needs to be renamed to _version.txt_ or removed. Then it will no longer be spuriously picked up by `#include <version>` due to `‑I src/utils/gzstream`.

**Comment by arjanvandervelde** [comment]
ok. thanks for pointing that out. I hadn't paid enough attention.

**Comment by arjanvandervelde** [comment]
https://github.com/macports/macports-ports/pull/6620
https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/22410

**Pull request merged**
