### PR TITLE
Bugfix/groupby test case difference

### PR DESCRIPTION
**Pull request by LukeGoodsell**
Fixes issue #472. Case of groupBy test directory is fixed, and test script exits with non-zero status in the event of an error. This allows the groupBy test to run, and a failure to be detected automatically.

### CODE REVIEW

**Comment by LukeGoodsell** [comment]
I've checked the Travis log - the failure is because the test script is trying to run test-sort.sh inside the test/slop directory. This has been a bug for all this time but wasn't detected by Travis because the test script just carries on and exits with a status of zero. This is fixed by pull request #474.

**Comment by arq5x** [comment]
If I understand the notes correctly, you believe this should be merged along with PR #474?

**Comment by LukeGoodsell** [comment]
Yes; now that #474 has been merged, the test passes. This pull request fixes the problem I have on Debian so that I can run `make test` and have it check the groupby tests.

However, looking through the output, there are many tests that report failing but `make test` still returns a zero exit status. E.g.: https://travis-ci.org/arq5x/bedtools2/jobs/196584033#L938

I think that each test script should be written to exit with a status of zero only if all the tests pass. This would allow users to run `make test && make install` and be confident that the build is good, and Travis CI will warn us about build-breaking changes.

I suggest:
1. this pull request be merged (to fix the case-sensitivity issue experienced by some OSes);
2. the test scripts be modified to run all the tests, but exit with non-zero if any test fails; and
3. the issues causing some tests to fail currently be fixed.

I'm happy to look into 2 and 3 if you like.

**Comment by arq5x** [comment]
Great, I will merge this and I completely agree re: 2 and 3, as these have been on my todo list for some time now. If you have time and interest, please feel free!

Best,
Aaron

**Comment by LukeGoodsell** [comment]
Hi Aaron,

I'll take a stab in my spare time over in this branch: https://github.com/arq5x/bedtools2/compare/master...LukeGoodsell:bugfix/make-test-fails-on-failure

You can see progress in Travis here: https://travis-ci.org/LukeGoodsell/bedtools2

Luke

**Pull request merged**
