### PR TITLE
fix negative slop

### PR DESCRIPTION
**Pull request by rishavray**
The negative slop issue #461 is fixed. Negative slop for for right and left end are also handled elegantly in edge cases. In case of crossover for start and end where start > end, the values are swapped to preserve integrity. If start is equal to end then the end is incremented by one, because BED files follow zero base co-ordinate system and the last position is ignored.

### CODE REVIEW

**Comment by arq5x** [comment]
Thanks so much for this! I will be merging it in in the next couple of weeks, as I integrate some new changes for the next release.

**Comment by arq5x** [comment]
Would you be willing to add a few test cases to ensure that future changes do not cause a regression (/tests/slop/test-slop.sh)?

**Comment by rishavray** [comment]
Sure. I will add the test cases I used to test the fix on my system.

**Comment by arq5x** [comment]
Excellent, thanks. Just ping when they are added!

**Comment by rishavray** [comment]
I have added a few test cases for slop. It covers the negative slop on both flanks inclusive of strandedness. Also overflows with negative slops on both flanks are tested. I hope these test cases suffice for now.

**Pull request merged**
