### PR TITLE
Consolidate pattern in top-level test script into loop.

### PR DESCRIPTION
**Pull request by skotchandsoda**
Every directory has one test script named _directory_-test.sh. So make test.sh a loop. While we're at it, add basic pass/fail counts and run every test by default.

If you want to stop running if a particular test fails, you can still do:

`sh -e test.sh`

### CODE REVIEW

**Comment by ghuls** [comment]
@arq5x The commit https://github.com/arq5x/bedtools2/commit/dad1fcbb6250ad4a566cdbc80915e6342c06c6ec breaks **make test**

I think it always says that all test of all tools work OK.

The following lines don't do what they are supposed to do:
> +    (cd $dir **bash** && bash test-$dir.sh) || FAILURES=$(expr $FAILURES + 1);
> +    if [ $? -eq 0 ]; then
> ...
> +        failed="**$failed** $dir"

**Comment by arq5x** [comment]
Hmm, it seems to work for me. I just intentionally changed a test file and it exited with 1 and said one test failed. What are you seeing when you run "make test"

**Comment by ghuls** [comment]
In my case I didn't have samtools in my PATH, so conversions from SAM to BAM fail.
```
$ make test

...
--------------------------
 Test Results             
--------------------------
Tools passing:  bamtobed bamtofastq bed12tobed6 closest cluster complement coverage expand fisher flank general genomecov getfasta groupby intersect jaccard makewindows map merge multicov reldist sample shift shuffle slop sort spacing split subtract
Tools with failures: 
Tests failed: 7
make: *** [test] Error 1
```

The line with **Tools with failures: ** is empty.

```
$ make test | grep fail
Failed to open BAM file one_block.bam
fail
Failed to open BAM file one_block.bam
fail
Failed to open BAM file two_blocks.bam
fail
Failed to open BAM file two_blocks.bam
fail
Failed to open BAM file three_blocks.bam
fail
Failed to open BAM file three_blocks.bam
fail
Failed to open BAM file three_blocks.bam
fail
Failed to open BAM file three_blocks.bam
Failed to open BAM file three_blocks.bam
Failed to open BAM file two_blocks_w_D.bam
fail
Failed to open BAM file two_blocks_w_D.bam
fail
Failed to open BAM file two_blocks_w_D.bam
fail
Failed to open BAM file two_blocks_w_D.bam
fail
fail
fail
fail
fail
Failed to open BAM file three_blocks.bam
fail
Failed to open BAM file three_blocks.bam
fail
Failed to open BAM file three_blocks.bam
fail
test-genomecov.sh: line 78: samtools: command not found
Failed to open BAM file -
fail
test-genomecov.sh: line 95: samtools: command not found
Failed to open BAM file -
fail
Failed to open BAM file three_blocks.bam
fail
Failed to open BAM file sam-w-del.bam
fail
Failed to open BAM file pair-chip.bam
fail
Failed to open BAM file chip.bam
fail
index file test.iupac.fa.fai not found, generating...
index file test.iupac.fa.fai not found, generating...
index file test.fa.fai not found, generating...
test-intersect.sh: line 208: samtools: command not found
fail
test-intersect.sh: line 217: samtools: command not found
test-intersect.sh: line 227: samtools: command not found
fail
test-intersect.sh: line 237: samtools: command not found
test-intersect.sh: line 247: samtools: command not found
fail
test-intersect.sh: line 256: samtools: command not found
test-intersect.sh: line 341: samtools: command not found
fail
test-intersect.sh: line 351: samtools: command not found
fail
fail
fail
fail
test-intersect.sh: line 728: samtools: command not found
test-intersect.sh: line 735: samtools: command not found
test-intersect.sh: line 742: samtools: command not found
fail
fail
test-intersect.sh: line 749: samtools: command not found
fail
test-intersect.sh: line 755: samtools: command not found
fail
fail
fail
fail
Tools with failures: 
Tests failed: 7
make: *** [test] Error 1
```

As you can see, there seems to be much more failures than only 7.

**Comment by arq5x** [comment]
Ah, I see. Yes, I am updating to just exit on first failure. Thus, the first tool to have >=1 failure with stop the testing.

**Pull request merged**
