### PR TITLE
Fixes that allow tests to complete succesfully

### PR DESCRIPTION
**Pull request by LukeGoodsell**
This pull request includes a number of changes to both the source code and the test scripts that allow the tests to (correctly) complete successfully, and so that running `make test` will exit with non-zero exit code if any test fails. It is therefore possible to do `make test && make install` and know that the install will only be performed if the tests passed, and that the tests should normally pass.

Important notes:
* To provide a cross-platform, seedable random source for `bedtools shuffle`, I have used the Mersenne Twister 19937 random generator, which was introduced as standard in C++11. This code will compile in g++ 4.6.3 (and possibly earlier) as the `-std=gnu++0x` flag has been added to the compilation options. It will probably cause builds in older compilers to fail, but I don't know what proportion of users may be affected. C++11 was finalised 5 years ago, and early versions were available in prior compilers, so hopefully most users will either be able to upgrade or will already have done so. I have added an optional command line flag to force using the old version, so users can type `make USE_RAND=1` and it will be backwards-compatible. Obviously, the shuffle tests only work if you build bedtools without this flag.
* For merge test 44b, a required file ("vcfSVtest.2.vcf") is missing. I have changed the script to skip this test if the file is not present, but the file should ideally be added.
* Previously, when the `fisher` command encountered an invalid ratio, it would either output "-nan" or "nan", depending on the build environment. To provide consistent output, I have forced it to use "-nan", as expected by the existing tests.
* The groupBy tests expect the file "test/groupby/test.bed", which is missing. I have created one that I think is similar to what the test expects.

### CODE REVIEW

**Comment by ghuls** [comment]
The failing test are quite annoying when trying to use **make test** to "*prove*" that a patch works.

@arq5x Can this be merged? Maybe it needs to be rebased on master.

**Comment by arq5x** [comment]
Sorry, I have not gotten around to merging this. Can you rebase and then I will merge it. Apologies!

**Comment by LukeGoodsell** [comment]
Hi @arq5x, I've rebased and made a small tweak: when sorting by size, if two intervals have the same size, different build environments would output them in different orders. To make it reproducible (and so the tests pass), I've made it sort same-length intervals by chrom & start.

Please do check that you're ok with the "important notes" in the PR.

**Comment by arq5x** [comment]
Thanks for this!  My only concern in the PR is the use of Mersenne, but your backwards compatibility functionality is great. I say we move forward with this and adjust if users run into major troubles.

**Pull request merged**
