### PR TITLE
Fixed tests so they actually run

### PR DESCRIPTION
**Pull request by LukeGoodsell**
* Fixed `test.sh`. It didn't run at all in its previous state - now it does.
    * `cd $tool bash` failed constitutively.
* Added `set -e` to all test scripts to fail on uncaught errors.
    * Needed to remove `return 0` from `check()` function to prevent premature failure of script.
* Fixed nested tests so that errors are reported.
    * E.g.: `test/intersect/sortAndNaming/test-sort-and-naming.sh` was running and failing, but the failure wasn't detected and reported to the user when running `make test`
* Fixed `NewChromsweep.cpp`'s 're-reun' typo.
* Added negative control test to check that test script is functioning correctly.
    * This should reduce the chance that a change can be introduced that silences errors in the tests.

### CODE REVIEW

**Comment by arq5x** [comment]
Thanks for digging into this problem! - I will have a look at your changes tonight!

**Comment by arq5x** [comment]
Thanks very much for doing this. It looks like there are now a few failures from a handful of tests in ```test/intersect/sortAndNaming/test-sort-and-naming.sh``` and some of the "closest" tests that arise because an error and some actual results are being report, yet "exp" expects only the error message. Would you be able to update those tests so that all tests pass in this PR?

```
--------------------------
 Test Results
--------------------------
Tools passing:  bamtobed bamtofastq bed12tobed6 cluster complement coverage expand fisher flank general genomecov getfasta groupby jaccard makewindows map merge multicov reldist sample shift shuffle slop sort spacing split subtract
Tools failing:  closest intersect negativecontrol
NB: the 'negativecontrol' test is supposed to fail. If it wasn't caught,
something went wrong with this test script.
make: *** [test] Error 1
```

**Comment by LukeGoodsell** [comment]
I've re-merged from master, but I'm unable to reproduce the errors you mention. I had already fixed some bugs with the two tests you mentioned as part of this PR; was your copy not updated, by any chance?

**Comment by arq5x** [comment]
I just cloned from your master and still get a few test failures in ```test/intersect/sortAndNaming/test-sort-and-naming.sh``` and in ```closest```.  Think I will just merge this PR and then fix the tests.
Thanks!

**Comment by arq5x** [comment]
Something is wonky because test 4 in ```test/intersect/sortAndNaming/test-sort-and-naming.sh``` should fail becaue when the  command is run manually ```obs``` contains output as well as the error message, yet ```exp`` only contains the error message. When I run ```test-sort-and-naming.sh``` within the ```sortAndNaming```, everything passes with "ok", yet when the test is run manually or via ```make test``` it fails.  Not sure what is happening, but will look into it. Any ideas?  Do you see the same on your end?

**Comment by LukeGoodsell** [comment]
Hi @arq5x,

Congratulations on becoming a tenured professor!

Sorry for the long message below; I'm trying to be thorough and precise.

I've now cloned a new copy of the repo and tried it in both OSX and Debian 8, but I'm not able to reproduce any error. I've tried running:

* `make test`
* `cd test/intersect/sortAndNaming/ && bash test-sort-and-naming.sh && cd ../../..`
* `BT=$(pwd)/bin/bedtools && cd test/intersect/sortAndNaming/ && $BT intersect -a q1_num.bed -b db1_num.bed db2_num.bed -sorted 2>&1 > /dev/null | cat - > obs && cd ../../..` (test 4 of `test-sort-and-naming.sh`)

... all of which exit with a status code of 0.

If I understand correctly, you're saying that test 4 of `test/intersect/sortAndNaming/test-sort-and-naming.sh` should produce data output as well as an error message. However, test 4 (to my eye) redirects the STDOUT content to /dev/null, and keeps only STDERR. Moreover, although the bedtools command exits with an exit code of 1, because of the pipe through cat, it is caught and hidden. Here is the test:

```
echo -e "    intersect.t04...\c"
echo \
"ERROR: Database file db1_num.bed contains chromosome chr3, but the query file does not.
       Please rerun with the -g option for a genome file.
       See documentation for details." >exp
$BT intersect -a q1_num.bed -b db1_num.bed db2_num.bed -sorted 2>&1 > /dev/null | cat - > obs
check obs exp
rm obs
```

If I run the command without the redirection and piping, I do get the data output and exit code 1:

```
# $BT intersect -a q1_num.bed -b db1_num.bed db2_num.bed -sorted     
chr1	10	20
chr1	80	100
chr2	50	80
chr2	100	120
ERROR: Database file db1_num.bed contains chromosome chr3, but the query file does not.
       Please rerun with the -g option for a genome file.
       See documentation for details.
# echo $?
1
```

My best guesses for what could be going wrong are:

* Do you have `set -o pipefail` in your login shell (e.g. in `~/.bash_login`)? That would cause the above test to fail when run manually, but not when called via `bash test-sort-and-naming.sh`.
* Is your default shell something other than bash? In `test/intersect/test-intersect.sh`, the `test-sort-and-naming.sh` script is being launched via `$SHELL` rather than `bash`, which could cause a difference in behaviour.
* When you run `make test`, it now outputs the message below, which might look like it has failed if you only see the last line:
```
...
Tools failing:  negativecontrol
NB: the 'negativecontrol' test is supposed to fail. If it wasn't caught, 
something went wrong with this test script.
```

In hindsight, I made a bad choice by putting the linebreak there.

**Comment by arq5x** [comment]
You nailed it - thought I was running bash on the test computer but it was zsh. Thanks very much for your help and for this important contribution!

**Pull request merged**
