### PR TITLE
betools pool

### PR DESCRIPTION
**Pull request by lindenb**
Hi again,

here is my idea.

I need to process to large number of BED items on my cluster but I needs to split my original BED file into a set of __N__ chunks so I can process each item using  __N__ parallel jobs .

I could just use linux `split` but I want that all parts to have the ~ same number of bases.

so I wrote `bedtools pool`  under src/pool

example:
```
 ./bin/bedtools pool -p _tmp -n 50 -i in.bed
$ ls _tmp.000*
_tmp.00001.bed  _tmp.00008.bed  _tmp.00015.bed  _tmp.00022.bed  _tmp.00029.bed  _tmp.00036.bed  _tmp.00043.bed  _tmp.00050.bed
_tmp.00002.bed  _tmp.00009.bed  _tmp.00016.bed  _tmp.00023.bed  _tmp.00030.bed  _tmp.00037.bed  _tmp.00044.bed
_tmp.00003.bed  _tmp.00010.bed  _tmp.00017.bed  _tmp.00024.bed  _tmp.00031.bed  _tmp.00038.bed  _tmp.00045.bed
_tmp.00004.bed  _tmp.00011.bed  _tmp.00018.bed  _tmp.00025.bed  _tmp.00032.bed  _tmp.00039.bed  _tmp.00046.bed
_tmp.00005.bed  _tmp.00012.bed  _tmp.00019.bed  _tmp.00026.bed  _tmp.00033.bed  _tmp.00040.bed  _tmp.00047.bed
_tmp.00006.bed  _tmp.00013.bed  _tmp.00020.bed  _tmp.00027.bed  _tmp.00034.bed  _tmp.00041.bed  _tmp.00048.bed
_tmp.00007.bed  _tmp.00014.bed  _tmp.00021.bed  _tmp.00028.bed  _tmp.00035.bed  _tmp.00042.bed  _tmp.00049.bed
```
check all parts have the ~ same  number of bases.

```
$ for F in _tmp.000*.bed; do awk '{N+=int($3)-int($2);} END{printf("%d bases %s lines:%d\n",N,FILENAME,NR);}' $F ; done
48583 bases _tmp.00001.bed lines:349
48670 bases _tmp.00002.bed lines:332
48567 bases _tmp.00003.bed lines:298
48587 bases _tmp.00004.bed lines:259
48702 bases _tmp.00005.bed lines:220
48694 bases _tmp.00006.bed lines:221
48548 bases _tmp.00007.bed lines:240
48577 bases _tmp.00008.bed lines:202
48623 bases _tmp.00009.bed lines:194
48648 bases _tmp.00010.bed lines:205
48743 bases _tmp.00011.bed lines:198
48594 bases _tmp.00012.bed lines:188
48872 bases _tmp.00013.bed lines:176
48764 bases _tmp.00014.bed lines:179
48564 bases _tmp.00015.bed lines:179
48694 bases _tmp.00016.bed lines:162
48791 bases _tmp.00017.bed lines:165
48698 bases _tmp.00018.bed lines:180
48891 bases _tmp.00019.bed lines:170
48696 bases _tmp.00020.bed lines:164
48884 bases _tmp.00021.bed lines:157
48591 bases _tmp.00022.bed lines:160
48534 bases _tmp.00023.bed lines:156
49207 bases _tmp.00024.bed lines:144
48672 bases _tmp.00025.bed lines:159
48887 bases _tmp.00026.bed lines:159
48612 bases _tmp.00027.bed lines:157
48865 bases _tmp.00028.bed lines:150
48622 bases _tmp.00029.bed lines:157
48892 bases _tmp.00030.bed lines:137
48881 bases _tmp.00031.bed lines:162
48856 bases _tmp.00032.bed lines:149
48557 bases _tmp.00033.bed lines:147
48646 bases _tmp.00034.bed lines:182
48626 bases _tmp.00035.bed lines:176
48563 bases _tmp.00036.bed lines:160
48716 bases _tmp.00037.bed lines:173
48556 bases _tmp.00038.bed lines:182
48634 bases _tmp.00039.bed lines:165
49462 bases _tmp.00040.bed lines:183
48930 bases _tmp.00041.bed lines:187
48575 bases _tmp.00042.bed lines:210
48563 bases _tmp.00043.bed lines:206
48604 bases _tmp.00044.bed lines:215
48676 bases _tmp.00045.bed lines:230
48651 bases _tmp.00046.bed lines:227
48886 bases _tmp.00047.bed lines:267
48659 bases _tmp.00048.bed lines:273
48564 bases _tmp.00049.bed lines:326
48649 bases _tmp.00050.bed lines:363
```

### CODE REVIEW

**Comment by arq5x** [comment]
Thanks for the contribution and the nice example use case, @lindenb!  A couple of comments:

1. Perhaps "split" would be a better name and it would allow the tool to either a) split a file by bases, b) split a file by chromosomes, or c) split a file by records?
2. I wonder if it would be worth supporting the ability to split/pool 1 or more files?

**Comment by arq5x** [comment]
I should also say that splitting based on the alternate methods is not necessary now, just tossing out ideas.  How do you feel about moving from "pool" to "split"?

**Comment by lindenb** [comment]
>How do you feel about moving from "pool" to "split"?
yes, no problem.

I just wanted to know if you're ok with this idea (I don't expect you're going to merge this for now). My current heuristic algorithm is slow and I think I can speed-up the process. I'm also thinking about pooling by mean-size, etc...

And I'm not even sure I've got time to work on my own idea too :-)

**Comment by arq5x** [comment]
Oh yes, of course.  It is a useful tool.

**Comment by lindenb** [comment]
OK, I've updated my code:
* moved to 'pool' to 'split'

* here is the help screen:
```
$ ./bin/bedtools split --help

Tool:    bedtools split
Version: v2.22.1-6-ge53d608-dirty
Summary: Split a Bed file.

Usage:   bedtools split [OPTIONS] -i <bed> -n number-of-files

Options: 
	-i|--input (file) BED input.
	-n|--number (int)	Number of beans to create.
	-p|--prefix (string)	output BED file prefix.
	-a|--algorithm (string) algorithm used to split data.
		* size (default): uses a heuristic algorithm to group the items so
		  all beans contain the ~ same number of bases
		* simple : slit items as they come
		  all beans contain the ~ same number of bases
	-h|--help	print help (this screen).
	-v|--version	print version.


This programs stores the BED items in memory.

```

* I've added a test under `test/split/test-split.sh`

* here is an example, output to stdout is filename/number-of-bases/number-of-bed-records
```
$ cat /dev/zero |tr "\0" "\n" | head -n 100000 |awk '{S=int(rand()*1000.0);E=S+int(rand()*100000); printf("chrX\t%d\t%d\n",S,E);}' | shuf |\
./bin/bedtools split -i - -p _tmp -n 20 -a size

_tmp.00001.bed	250263515	5000
_tmp.00002.bed	250263514	5000
_tmp.00003.bed	250263509	5001
_tmp.00004.bed	250263509	5000
_tmp.00005.bed	250263509	5000
_tmp.00006.bed	250263508	5000
_tmp.00007.bed	250263508	5001
_tmp.00008.bed	250263515	5000
_tmp.00009.bed	250263508	5000
_tmp.00010.bed	250263508	5000
_tmp.00011.bed	250263508	5000
_tmp.00012.bed	250263509	5000
_tmp.00013.bed	250263509	5000
_tmp.00014.bed	250263507	5000
_tmp.00015.bed	250263506	5000
_tmp.00016.bed	250263506	5000
_tmp.00017.bed	250263508	5000
_tmp.00018.bed	250263514	5000
_tmp.00019.bed	250263504	4999
_tmp.00020.bed	250263506	4999
```

**Comment by arq5x** [comment]
Very cool!  Will look closely later tonight or early tomorrow - have to wrap up some grant writing.  Thanks for this, Pierre!

**Comment by arq5x** [comment]
This looks really nice, Pierre.  I have two questions:

1. What is meant by a "bean"?  Is that a term for each individual output file?
2. Based on the help for `-a`, I can't tell exactly how the two algorithms differ.  Could you elaborate/clarify the help a bit more?

Thanks!

**Comment by lindenb** [comment]
> What is meant by a "bean"? Is that a term for each individual output file?

yes, just a collection of BED items

> Based on the help for -a, I can't tell exactly how the two algorithms differ. Could you elaborate/clarify the help a bit more?

* simple: if n==2: put BED[0] in bean[0], put BED[1] in bean[1], put BED[2] in bean[0], put BED[3] in bean[1], put BED[4] in bean[0], put BED[5] in bean[1]....  the 'beans' should have the ~ same size if the BED items have the ~ same size. For now I put everything in memory but if 'n'< FILEOPEN_MAX, we could also open 'n' FILE for writing with storing everything in memory.

* size:  if n==2: put BED[0] in bean[0], put BED[1] in bean[1], find the best bean to put BED[2],   find the best bean to put BED[3] ( best == lowest chande in the std deviation of sizes, I wonder if just  using the smallest bean would work ?)

P.

**Comment by arq5x** [comment]
Thanks Pierre, this is very helpful!  Let's merge it in and make it available in the next release (<2 weeks away, if all goes as planned).

**Comment by lindenb** [comment]
Thanks ! While you were merging I've implemented my point about 'simple'. I'm going to submit another merge request soon :-)

**Comment by lindenb** [comment]
FYI... and then I realized that I should have written 'bin', not 'bean' :-D #syntax #typo #french

**Comment by arq5x** [comment]
Ha, no big deal. I thought that might have been the case.  I pulled in the changes and just pushed some minor cleanup back.  I think the only other feature that it needs to be a bit more general is the ability to pass a header on to each of the split files. That way, VCF and GFF are equally well supported through the API.  I guess the extension would have to be inferred or just ignored.

**Pull request merged**
