### PR TITLE
Allows chr contig names

### PR DESCRIPTION
**Pull request by bwlang**
chr contig names were valid  in 2.26.0
but not after 97c0176b5f8be2577cadb65763d8df8a42b12cb8

### CODE REVIEW

**Comment by bwlang** [comment]
@arq5x 
thanks for bedtools! let me know if you would like a different approach to this issue...

**Comment by bwlang** [comment]
not sure about assuming that there a 6th element in tmp... maybe need a bounds check?  (isspace did it so I did too :)

**Comment by bwlang** [comment]
@arq5x 
Anything I can do to make this easier to consume?

**Comment by arq5x** [comment]
Sorry, just didn't have the bandwidth. Merging now!

**Pull request merged**
