### PR TITLE
Int64 chrpos

### PR DESCRIPTION
**Pull request by brentp**
opening this to get pointers on any obvious problems or tests to add.

this change CHRPOS to int64_t (instead of uint32).
there were several places in the bedtools code that used int instead of CHRPOS because it was allowing negative values (or deltas).
this unifies those to a standard int64_t.

this will increase the amount of memory for the non-streaming stuff. 

this probably needs a few more things to integrate with the UCSC binning setup as that gets converted to handle int64's .

to further work on this, use

```
make DEBUG=1 2>err
```
then look in `err` for any messages with `CHRPOS`. I didn't convert anything related to bam since that is limited to 32bit in htslib anyway. I also left bedFile.h and bedFilePE.h as those depend on the bin tree changes.

### CODE REVIEW

**Comment by jmarshall** [comment]
There are now a million warnings of the form

```
src/utils/bedFile/bedFile.h:939:62: warning: format specifies type 'long' but
                                    the argument has type 'CHRPOS' (aka 'long long')
                printf ("%s\t%ld\t%ld\t", bed.chrom.c_str(), start, end);
                             ~~~                             ^~~~~
```

Do you folks have a plan for fixing this? Ideal would be to convert printfs to use std::cout instead (as the code would be the same whatever type CHRPOS is), but this will be non-trivial for fprintfs inside functions that are given a `FILE*` as the callers would need to be converted to use iostreams instead too.

The paste-over-the-cracks approach would be to fix the format strings to (indirectly) use \<inttypes.h\>'s PRIdNN-style macro instead. I have such changes prepared that I could turn into a PR if that would be useful…?

**Comment by brentp** [comment]
that would be great to have a PR that uses inttypes.

**Comment by arq5x** [comment]
Yes, tackling the flood of warnings is next in the list, so it would be great if you have a PR that tackles this. Thanks for your help, @jmarshall !

**Comment by jmarshall** [comment]
Okay, coming soon. Just a couple more source files to go through… :smile:

**Comment by jmarshall** [comment]
This is now #701.

**Pull request merged**
